### ISSUE TITLE
请输入验证码,云盘线程重新监听

### ISSUE THREAD

**Issue by doulala1986** [dounine/clouddisk#27]
`
12:08:14,335  INFO main deserializer.BaseResponseHandle:53 - 验证码(解析器) -> 响应结果:{"errno":"0","errmsg":"OK","errinfo":{"en":"OK"},"captchaFlag":true,"captchaUrl":"http:\/\/passport.360.cn\/captcha.php?m=create&app=i360&scene=login&userip=ONTSG214T/+bzPlXQQA+aA==&level=default&sign=b3106f&r=1471838894"}
Exception in thread "main" java.lang.NullPointerException
	at com.dounine.clouddisk360.executor.Main.qianshao(Main.java:141)
	at com.dounine.clouddisk360.executor.Main.main(Main.java:36)
12:18:15,024  INFO Thread-2 deserializer.BaseResponseHandle:53 - 登录令牌(解析器) -> 响应结果: login.setSigCallback({"errno":0,"errmsg":"","token":"2f767e8e891713aa"})
12:18:15,086  INFO Thread-2 deserializer.BaseResponseHandle:53 - 用户登录(解析器) -> 响应结果:<script type='text/javascript'>location.href='http://yunpan.360.cn/psp_jump.html?fun=totalLogin.loginCallbackFun&errno=78002&errmsg=请输入验证码&errdetail={"captchaUrl":"https:\/\/passport.360.cn\/captcha.php?m=create&app=i360&scene=login&userip=ONTSG214T%2F%2BbzPlXQQA%2BaA%3D%3D&level=default&sign=b3106f&r=1471839495"}&';</script>
12:18:15,106  INFO Thread-2 captthread.CaptchaThreadValidator:173 - 用户无需处理验证码
12:18:15,106  INFO Thread-2 captthread.CaptThread:32 - 云盘线程验证启动
12:18:15,138  INFO Thread-2 deserializer.BaseResponseHandle:53 - 验证码(解析器) -> 响应结果:{"errno":"0","errmsg":"OK","errinfo":{"en":"OK"},"captchaFlag":true,"captchaUrl":"http:\/\/passport.360.cn\/captcha.php?m=create&app=i360&scene=login&userip=ONTSG214T/+bzPlXQQA+aA==&level=default&sign=b3106f&r=1471839495"}
12:18:15,162  INFO Thread-2 captthread.CaptThread:107 - 请输入验证码,云盘线程重新监听

`

我在我的User目录下找到了验证码，但是如何输入？

**Comment by dounine** [comment]
验证码是，要通过web的方式调用输入的，用main方法无法测试

**Comment by doulala1986** [comment]
谢谢大神，请问如果是web方式的话？我怎么获取到验证码输入页面呢？

**Comment by dounine** [comment]
这是web的例子：https://github.com/dounine/clouddisk-web

**Comment by doulala1986** [comment]
十分感谢您的代码和您的帮助~
